spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaSpringMVC?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
org:
  apache:
    jasper:
      compiler:
        TldLocationsCache:
          level: FINE
      servlet:
        TldScanner:
          level: FINE
